// Code generated by ctxboot; DO NOT EDIT.

package main

import (
	"github.com/iondodon/ctxboot"
	"reflect"
	"log"
	"fmt"
	
)

// Context embeds ComponentContext and adds getter methods
type Context struct {
	*ctxboot.ComponentContext
}

// RegisterComponent registers a component instance and automatically deduces its type
func (cc *Context) RegisterComponent(instance interface{}) error {
	if instance == nil {
		return fmt.Errorf("cannot register nil component")
	}
	return cc.SetComponent(reflect.TypeOf(instance), instance)
}

// InjectComponents initializes all registered components and their dependencies
func (cc *Context) InjectComponents() error {
	return cc.InitializeComponents()
}

// RegisterScanedComponenets registers all components
func (cc *Context) RegisterScanedComponenets() error {
	// Register components in dependency order
	
	// Register LoggerConfig
	if err := cc.SetComponent(reflect.TypeOf((*LoggerConfig)(nil)), &LoggerConfig{}); err != nil {
		log.Fatalf("Failed to register component %s: %v", "LoggerConfig", err)
	}
	
	// Register DatabaseConfig
	if err := cc.SetComponent(reflect.TypeOf((*DatabaseConfig)(nil)), &DatabaseConfig{}); err != nil {
		log.Fatalf("Failed to register component %s: %v", "DatabaseConfig", err)
	}
	
	
	return nil
}

// NewContext creates a new context
func NewContext() *Context {
	return &Context{ctxboot.Boot()}
}

// Component getter methods

// GetLoggerConfig returns the LoggerConfig component
func (cc *Context) GetLoggerConfig() (*LoggerConfig, error) {
	component, err := cc.GetComponent(reflect.TypeOf((*LoggerConfig)(nil)))
	if err != nil {
		return nil, err
	}
	return component.(*LoggerConfig), nil
}

// GetDatabaseConfig returns the DatabaseConfig component
func (cc *Context) GetDatabaseConfig() (*DatabaseConfig, error) {
	component, err := cc.GetComponent(reflect.TypeOf((*DatabaseConfig)(nil)))
	if err != nil {
		return nil, err
	}
	return component.(*DatabaseConfig), nil
}

