// Code generated by ctxboot; DO NOT EDIT.

package main

import (
	"github.com/iondodon/ctxboot"
	"reflect"
	"log"
	
)

// LoadContext registers and initializes all components
func LoadContext(cc *ctxboot.ComponentContext) error {
	// Register components in dependency order
	
	// Register EnglishGreeter
	if err := cc.SetComponent(reflect.TypeOf((*EnglishGreeter)(nil)), &EnglishGreeter{}); err != nil {
		log.Fatalf("Failed to register component %s: %v", "EnglishGreeter", err)
	}
	
	
	// Initialize all components after registration
	return cc.InitializeComponents()
}
