// Code generated by ctxboot; DO NOT EDIT.

package main

import (
	"github.com/iondodon/ctxboot"
	"reflect"
	"log"
	"fmt"
	
)

// Context embeds ComponentContext and adds getter methods
type Context struct {
	*ctxboot.ComponentContext
}

// RegisterComponent registers a component instance and automatically deduces its type
func (cc *Context) RegisterComponent(instance interface{}) error {
	if instance == nil {
		return fmt.Errorf("cannot register nil component")
	}
	return cc.SetComponent(reflect.TypeOf(instance), instance)
}

// InjectComponents initializes all registered components and their dependencies
func (cc *Context) InjectComponents() error {
	return cc.InitializeComponents()
}

// RegisterScanedComponenets registers all components
func (cc *Context) RegisterScanedComponenets() error {
	// Register components in dependency order
	
	// Register EnglishGreeter
	if err := cc.SetComponent(reflect.TypeOf((*EnglishGreeter)(nil)), &EnglishGreeter{}); err != nil {
		log.Fatalf("Failed to register component %s: %v", "EnglishGreeter", err)
	}
	
	
	return nil
}

// NewContext creates a new context
func NewContext() *Context {
	return &Context{ctxboot.Boot()}
}

// Component getter methods

// GetEnglishGreeter returns the EnglishGreeter component
func (cc *Context) GetEnglishGreeter() (*EnglishGreeter, error) {
	component, err := cc.GetComponent(reflect.TypeOf((*EnglishGreeter)(nil)))
	if err != nil {
		return nil, err
	}
	return component.(*EnglishGreeter), nil
}

