// Code generated by ctxboot; DO NOT EDIT.

package main

import (
	"github.com/iondodon/ctxboot"
	"reflect"
	"log"
	
)

// Context embeds ComponentContext and adds getter methods
type Context struct {
	*ctxboot.ComponentContext
}

// LoadContext registers and initializes all components and returns a Context
func LoadContext() (*Context, error) {
	cc := &Context{ctxboot.Boot()}
	
	// Register components in dependency order
	
	// Register UserService
	if err := cc.SetComponent(reflect.TypeOf((*UserService)(nil)), &UserService{}); err != nil {
		log.Fatalf("Failed to register component %s: %v", "UserService", err)
	}
	
	
	// Initialize all components after registration
	if err := cc.InitializeComponents(); err != nil {
		return nil, err
	}
	
	return cc, nil
}

// Component getter methods

// GetUserService returns the UserService component
func (cc *Context) GetUserService() (*UserService, error) {
	component, err := cc.GetComponent(reflect.TypeOf((*UserService)(nil)))
	if err != nil {
		return nil, err
	}
	return component.(*UserService), nil
}

