// Code generated by ctxboot; DO NOT EDIT.

package main

import (
	"github.com/iondodon/ctxboot"
	"reflect"
)

func init() {
	cc := ctxboot.Boot()
	
	if err := cc.SetComponent(reflect.TypeOf(&Database{}), &Database{}); err != nil {
		panic(err)
	}
	
	if err := cc.SetComponent(reflect.TypeOf(&UserRepository{}), &UserRepository{}); err != nil {
		panic(err)
	}
	
	if err := cc.SetComponent(reflect.TypeOf(&UserService{}), &UserService{}); err != nil {
		panic(err)
	}
	
}
